### ISSUE TITLE
Incompatible with Puma 6

### ISSUE THREAD

**Issue by amrrbakry** [babbel/puma-plugin-telemetry#18]
Hi,

we are in the process of upgrading our Rails app to Puma 6 and we are getting this error:

```zsh
# with Puma 6 in the Gemfile 

/Users/amr.mohamed/.rvm/gems/ruby-3.1.2/gems/puma-plugin-telemetry-1.1.1/lib/puma/plugin/telemetry.rb:67:in `start': 
undefined method `log' for #<Puma::Events:0x000000011585e498 @hooks={}> (NoMethodError)

            launcher.events.log 'plugin=telemetry msg="disabled, exiting..."'
```

this is because in Puma 6, the events class was split into `Puma::Events` and `Puma::LogWriter`, and the latter now contains the `log` and `debug` methods. 

I think I can do a PR to fix this. WDYT?

**Comment by soulim** [comment]
`Puma::Events` object was split into two separate objects, `Events` and `LogWriter` in https://github.com/puma/puma/pull/2798.
